FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY patches ./patches
RUN npm ci --legacy-peer-deps

COPY . .

ARG PAYLOAD_SECRET
ARG DATABASE_URL
ENV NODE_ENV=production
ENV PAYLOAD_SECRET=${PAYLOAD_SECRET}
ENV DATABASE_URL=${DATABASE_URL}

RUN mkdir -p src/generated && npm run generate:types
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
